stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: $DOCKER_USERNAME/your_docker_img_name:latest

##Build Docker image
build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

## Deploy to EC2
deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$EC2_PUBLIC_IP" >> ~/.ssh/known_hosts
  script:
  - ssh ec2-user@"$EC2_PUBLIC_IP" "
      command -v docker || { echo 'Docker not found, installing...'; sudo yum install -y docker && sudo service docker start; };
      docker login -u \"$DOCKER_USERNAME\" -p \"$DOCKER_PASSWORD\" ;
      sudo docker stop \$(docker ps -qa) ;
      sudo docker rm \$(docker ps -qa) ;
      sudo docker rmi \$(docker images -qa) ;
      docker run -d --name your_docker_img_name --restart=unless-stopped -p 3000:3000 $DOCKER_IMAGE
    "
  only:
    - qa
